# Generated by Django 6.0 on 2026-01-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_commission_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='balance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='balance_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True),
        ),
    ]
