# Generated by Django 6.0 on 2026-01-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_commission_balance_paid_commission_balance_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('advance_paid', 'Advance Paid'), ('in_progress', 'In Progress'), ('completed', 'Work Completed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
