# Generated by Django 6.0 on 2026-01-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_commission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_title',
            field=models.CharField(default='Untitled Artwork', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='untitled', upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
