# Generated by Django 6.0 on 2026-01-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_artwork_artwork_title_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_title',
            field=models.CharField(max_length=200),
        ),
    ]
