# Generated by Django 6.0 on 2026-01-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_user_bio_user_full_name_user_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
