# Generated by Django 6.0 on 2026-01-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_remove_user_full_name_user_name_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='price',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
    ]
