# Generated by Django 6.0 on 2026-02-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
