# Generated by Django 6.0 on 2026-02-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_commission_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
