# Generated by Django 6.0 on 2026-03-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_commission_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_artist', 'New Artist Request'), ('commission_request', 'Commission Request'), ('advance_paid', 'Advance Paid'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shipped', 'Shipped')], max_length=30),
        ),
    ]
