# Generated by Django 6.0 on 2026-01-08 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_commission_accepted_at_commission_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='final_artwork',
        ),
        migrations.AddField(
            model_name='commission',
            name='advance_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='required_date',
            field=models.DateField(default=datetime.date(2026, 1, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('advance_paid', 'Advance Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
