# Generated by Django 6.0 on 2026-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_remove_commission_final_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
