# Generated by Django 6.0 on 2026-01-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_commission_advance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commission',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
