# Generated by Django 6.0 on 2026-01-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_commission_advance_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
