# Generated by Django 6.0 on 2026-01-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_commission_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='status',
        ),
    ]
